# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
@a = User.create(:name => 'Jordan Yeo', :email => 'jordan@jordanyeo.com', :password => 'changeme', :password_confirmation => 'changeme', :admin => 'true')
@a = User.create(:name => 'John Smith', :email => 'john@example.com', :password => 'changeme', :password_confirmation => 'changeme')
@e = Event.create(:name => 'Inaugural CityRush', :scheduled_at => '04/09/2016 11:00AM', :description => 'The very first CityRush that will take you around #YEG')
@c = Clue.create(:name => 'Fruit and Veg', :event_id => @e.id, :description => 'This site was originally used to grow fruits and vegetables for local consumption. Featuring historic architecture not typical of Canada, and many walking paths, this area has been managed since 2000 by a society of local Edmontonians. Check in with your team while over the water.', :answer => '99')
@c = Clue.create(:name => 'Confederation', :event_id => @e.id, :description => ' A true confederate checkpoint! Once known as the “Galician”, this spot used to be known for its squatters and their tents. You can see this checkpoint from multiple angles, but check in with your team while on the “last step” with the target in the background. Let us know just how many wooden steps it takes to get to the top to earn a two minute bonus.', :answer => '99')
@c = Clue.create(:name => 'Statue', :event_id => @e.id, :description => 'This statue was built to commemorate a visit from the Pope. While “nestled” beneath the statue, one can take in a spectacular view of downtown Edmonton. Check in at this waypoint with your team beneath the statue, and let us know the first five words on the plaque commemorating this special landmark.', :answer => '99')
@c = Clue.create(:name => 'Window Dressing', :event_id => @e.id, :description => 'Named after the first mayor of one of Edmonton’s many communities, this building has now been standing for over 100 years. Uses have varied, from local education to the offices of the Commonwealth Games. Today, Edmontonians of all ages visit this location, sometimes staying overnight. Check in with your team at the front door, then tell us the total number of windows in the building.', :answer => '99')
@c = Clue.create(:name => 'Bridges', :event_id => @e.id, :description => 'Originally the site of construction for one of Edmonton’s many bridges, this location soon changed after the second world war. Originally constructed at Pigeon Lake, this building was then transported to Edmonton where it now stands at it’s final resting place. Take in the spectacular views of the river, check in at the front door with your team, and tell us the last five words on the commemorative plaque you’ll find on this site.', :answer => '99')